version: "3"

services:
  interactive_shell:
    image: alpine:3
    tty: true
    stdin_open: true
    environment:
      - HOME=/root
      - TERM=xterm
    volumes:
      - ./bashrc:/root/.bashrc
      - ./bash_aliases:/root/.bash_aliases
    command: sh -c "apk add --no-cache bash curl iputils && \
                    echo 'source /root/.bash_aliases' >> /root/.bashrc && \
                    /bin/bash"
